### ISSUE TITLE
Could not find declared class 'logstash-reporter' in /etc/puppet/manifests/nodes/host.pp:22

### ISSUE THREAD

**Issue by udaivizury** [elastic/puppet-logstash-reporter#19]
Hi,

I just downloaded the puppet-logstash-reporter module and installed it. But getting error when trying to deploy it.

Here is my config :
=/etc/puppet/manifests/nodes/xxx.pp
```
node 'xxx.example.com {
class { 'logstash-reporter': }
#logstash_host => 'xxxx.example.com',
#	logstash_port => '5050',
#}
}
```
And the module lies in /etc/puppet/modules/logstash-reporter ( renamed from puppet-logstash-reporter ).
Here is the required snippet of the init.pp file.
```
class logstash_reporter (
  $logstash_host = 'logstash.domain.com',
  $logstash_port = 5050,
  $config_file   = $::logstash_reporter::params::config_file,
  $config_owner  = $::logstash_reporter::params::config_owner,
  $config_group  = $::logstash_reporter::params::config_group,
) inherits logstash_reporter::params {
  file { $config_file:
    ensure  => file,
    owner   => $config_owner,
    group   => $config_group,
    mode    => '0444',
    content => template('logstash_reporter/logstash.yaml.erb'),
  }
}
```

When I use the above two in the manifests, I get following error.
```
Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
Info: Retrieving pluginfacts
Error: /File[/var/lib/puppet/facts.d]: Could not evaluate: Could not retrieve information from environment production source(s) puppet://puppet/pluginfacts
Info: Retrieving plugin
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class logstash-reporter at /etc/puppet/manifests/nodes/xxx.pp:22 on node host.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I am not sure where I am going wrong or if it is an issue inherent with the module. I would appreciate your guidance.

Thanks,
Udai

**Comment by electrical** [comment]
Hi @udaivizury Thank you for the report.

I've updated your first post to be a bit clearer with code blocks, was a bit hard to read.
It seems that you refer to the class with `logstash-reporter` which should be `logstash_reporter` ( underscore instead of dash )
Could you try that and see if it works?

**Comment by udaivizury** [comment]
Hi,

Thanks @electrical . I think you solved my problem.  I was using logstash-reporter instead of logstash_reporter.

Regards,
Udai
