### ISSUE TITLE
Forge release

### ISSUE THREAD

**Issue by bodgit** [elastic/puppet-logstash-reporter#6]
Is this module going to be released to the Puppet forge?

There is currently only https://forge.puppetlabs.com/evenup/logstash_reporter which ironically is a fork of this module, yet still uses the older V0 event format.

**Comment by electrical** [comment]
Sorry for the delay, I will be picking this up and doing a release tomorrow or early next week.

**Comment by kariboe** [comment]
Any news on the release?

**Comment by electrical** [comment]
Hi,

There have been some local issues i'm trying to find out to make sure it works like expected.
With the tests i haven't been able to test out everything yet for some weird reason.

**Comment by kariboe** [comment]
Thanks for the quick reply. I'll keep an eye on this repo. Let me know if I can test/help.

**Comment by electrical** [comment]
And its out there :-)  https://forge.puppetlabs.com/elasticsearch/logstash_reporter
